# Project Notebook
## Step 1: Data Preparation

### Task 1:

In [24]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

nhanes = pd.read_csv('nhanes.csv')
nhanes.head()

,SEQN,SDDSRVYR,RIDSTATR,RIAGENDR,RIDAGEYR,RIDRETH1,DMQMILIZ,DMDBORN4,DMDYRUSR,DMDEDUC2,...,HIQ032F,HIQ032H,HIQ032I,HIQ210,INDFMMPC,INQ300,IND310,BPXOSY1,BPXODI1,LBXTC
0,132141.0,12.0,2.0,2.0,56.0,4.0,2.0,1.0,NaN,5.0,...,NaN,NaN,NaN,2.0,3.0,1.0,NaN,115.0,70.0,205.0
1,136977.0,12.0,2.0,1.0,29.0,3.0,2.0,2.0,2.0,5.0,...,NaN,NaN,NaN,2.0,3.0,2.0,2.0,125.0,71.0,193.0
2,134280.0,12.0,2.0,2.0,25.0,3.0,2.0,1.0,NaN,5.0,...,NaN,NaN,NaN,2.0,3.0,1.0,NaN,111.0,69.0,87.0
3,132522.0,12.0,2.0,2.0,64.0,3.0,2.0,1.0,NaN,4.0,...,NaN,NaN,NaN,2.0,NaN,NaN,NaN,113.0,90.0,215.0
4,138725.0,12.0,2.0,2.0,28.0,3.0,2.0,1.0,NaN,5.0,...,NaN,NaN,NaN,2.0,3.0,1.0,NaN,114.0,69.0,215.0

In [25]:
nhanes.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5703 entries, 0 to 5702
Data columns (total 33 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   SEQN      5703 non-null   float64
 1   SDDSRVYR  5703 non-null   float64
 2   RIDSTATR  5703 non-null   float64
 3   RIAGENDR  5703 non-null   float64
 4   RIDAGEYR  5703 non-null   float64
 5   RIDRETH1  5703 non-null   float64
 6   DMQMILIZ  5703 non-null   float64
 7   DMDBORN4  5703 non-null   float64
 8   DMDYRUSR  1140 non-null   float64
 9   DMDEDUC2  5449 non-null   float64
 10  DMDMARTZ  5448 non-null   float64
 11  DMDHHSIZ  5703 non-null   float64
 12  WTINT2YR  5703 non-null   float64
 13  WTMEC2YR  5703 non-null   float64
 14  ALQ111    4929 non-null   float64
 15  ALQ121    4429 non-null   float64
 16  ALQ130    3657 non-null   float64
 17  ALQ151    4409 non-null   float64
 18  ALQ170    2113 non-null   float64
 19  HIQ011    5703 non-null   float64
 20  HIQ032A   3037 non-null   float64
 21  HIQ032B   1977 non-null   float64
 22  HIQ032D   841 non-null    float64
 23  HIQ032F   238 non-null    float64
 24  HIQ032H   434 non-null    float64
 25  HIQ032I   225 non-null    float64
 26  HIQ210    5218 non-null   float64
 27  INDFMMPC  5229 non-null   float64
 28  INQ300    5230 non-null   float64
 29  IND310    2579 non-null   float64
 30  BPXOSY1   5510 non-null   float64
 31  BPXODI1   5510 non-null   float64
 32  LBXTC     5145 non-null   float64
dtypes: float64(33)
memory usage: 1.4 MB

### Task 2:

### Task 3:

In [26]:
# Create helper function to classify blood pressure for every row
def classify_bp(row):
    systolic_bp = row["BPXOSY1"]
    diastolic_bp = row["BPXODI1"]
    # Edge case where either systolic or diastolic are missing
    if pd.isna(systolic_bp) or pd.isna(diastolic_bp):
        return np.nan
    if systolic_bp < 120 and diastolic_bp < 80:
        return "normal"
    else:
        return "abnormal"

In [27]:
# Pass in function to every row to classify and label the new BP column
nhanes['BP'] = nhanes.apply(classify_bp, axis=1)
nhanes['BP'].value_counts()

BP
abnormal    3119
normal      2391
Name: count, dtype: int64

In [28]:
nhanes['BP']

0         normal
1       abnormal
2         normal
3       abnormal
4         normal
          ...
5698      normal
5699    abnormal
5700    abnormal
5701    abnormal
5702    abnormal
Name: BP, Length: 5703, dtype: object

In [29]:
def classify_cholesterol(value):
    if pd.isna(value):
        return np.nan
    if value < 200:
        return "normal"
    elif value <= 239:
        return "borderline"
    else:
        return "high"

In [30]:
nhanes["CHOL"] = nhanes["LBXTC"].apply(classify_cholesterol)
nhanes["CHOL"].value_counts()

CHOL
normal        3325
borderline    1257
high           563
Name: count, dtype: int64

In [31]:
nhanes = nhanes.drop(columns=['BPXOSY1', 'BPXODI1', 'LBXTC'])

In [32]:
nhanes[["BP", "CHOL"]].head()

         BP        CHOL
0    normal  borderline
1  abnormal      normal
2    normal      normal
3  abnormal  borderline
4    normal  borderline

### Task 4:

In [33]:
from sklearn.model_selection import train_test_split

bp_ernazarov = nhanes.copy()
chol_ernazarov = nhanes.copy()

In [34]:
bp_training_ernazarov, bp_test_ernazarov = train_test_split(bp_ernazarov, train_size=0.8, test_size=0.2, random_state=42)

In [35]:
chol_training_ernazarov, chol_test_ernazarov = train_test_split(chol_ernazarov, train_size=0.8, test_size=0.2, random_state=42)

In [36]:
bp_training_ernazarov.head()

,SEQN,SDDSRVYR,RIDSTATR,RIAGENDR,RIDAGEYR,RIDRETH1,DMQMILIZ,DMDBORN4,DMDYRUSR,DMDEDUC2,...,HIQ032D,HIQ032F,HIQ032H,HIQ032I,HIQ210,INDFMMPC,INQ300,IND310,BP,CHOL
1892,132398.0,12.0,2.0,1.0,31.0,2.0,2.0,2.0,2.0,5.0,...,NaN,NaN,NaN,NaN,NaN,1.0,2.0,4.0,normal,borderline
3196,134479.0,12.0,2.0,1.0,55.0,3.0,2.0,1.0,NaN,5.0,...,NaN,NaN,NaN,NaN,NaN,7.0,2.0,1.0,normal,normal
3443,139895.0,12.0,2.0,1.0,73.0,2.0,2.0,2.0,6.0,5.0,...,4.0,NaN,NaN,NaN,2.0,2.0,2.0,4.0,normal,normal
4993,132502.0,12.0,2.0,1.0,69.0,2.0,1.0,1.0,NaN,4.0,...,NaN,NaN,NaN,NaN,2.0,3.0,2.0,3.0,abnormal,normal
1071,133635.0,12.0,2.0,1.0,44.0,3.0,2.0,1.0,NaN,4.0,...,NaN,NaN,NaN,NaN,2.0,3.0,1.0,NaN,normal,borderline

In [37]:
chol_training_ernazarov.head()

,SEQN,SDDSRVYR,RIDSTATR,RIAGENDR,RIDAGEYR,RIDRETH1,DMQMILIZ,DMDBORN4,DMDYRUSR,DMDEDUC2,...,HIQ032D,HIQ032F,HIQ032H,HIQ032I,HIQ210,INDFMMPC,INQ300,IND310,BP,CHOL
1892,132398.0,12.0,2.0,1.0,31.0,2.0,2.0,2.0,2.0,5.0,...,NaN,NaN,NaN,NaN,NaN,1.0,2.0,4.0,normal,borderline
3196,134479.0,12.0,2.0,1.0,55.0,3.0,2.0,1.0,NaN,5.0,...,NaN,NaN,NaN,NaN,NaN,7.0,2.0,1.0,normal,normal
3443,139895.0,12.0,2.0,1.0,73.0,2.0,2.0,2.0,6.0,5.0,...,4.0,NaN,NaN,NaN,2.0,2.0,2.0,4.0,normal,normal
4993,132502.0,12.0,2.0,1.0,69.0,2.0,1.0,1.0,NaN,4.0,...,NaN,NaN,NaN,NaN,2.0,3.0,2.0,3.0,abnormal,normal
1071,133635.0,12.0,2.0,1.0,44.0,3.0,2.0,1.0,NaN,4.0,...,NaN,NaN,NaN,NaN,2.0,3.0,1.0,NaN,normal,borderline

### Task 5: