# Project Notebook
## Step 1: Data Preparation

### Task 1:

In [32]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

nhanes = pd.read_csv('nhanes.csv')
nhanes.head()

,SEQN,SDDSRVYR,RIDSTATR,RIAGENDR,RIDAGEYR,RIDRETH1,DMQMILIZ,DMDBORN4,DMDYRUSR,DMDEDUC2,...,HIQ032F,HIQ032H,HIQ032I,HIQ210,INDFMMPC,INQ300,IND310,BPXOSY1,BPXODI1,LBXTC
0,132141.0,12.0,2.0,2.0,56.0,4.0,2.0,1.0,NaN,5.0,...,NaN,NaN,NaN,2.0,3.0,1.0,NaN,115.0,70.0,205.0
1,136977.0,12.0,2.0,1.0,29.0,3.0,2.0,2.0,2.0,5.0,...,NaN,NaN,NaN,2.0,3.0,2.0,2.0,125.0,71.0,193.0
2,134280.0,12.0,2.0,2.0,25.0,3.0,2.0,1.0,NaN,5.0,...,NaN,NaN,NaN,2.0,3.0,1.0,NaN,111.0,69.0,87.0
3,132522.0,12.0,2.0,2.0,64.0,3.0,2.0,1.0,NaN,4.0,...,NaN,NaN,NaN,2.0,NaN,NaN,NaN,113.0,90.0,215.0
4,138725.0,12.0,2.0,2.0,28.0,3.0,2.0,1.0,NaN,5.0,...,NaN,NaN,NaN,2.0,3.0,1.0,NaN,114.0,69.0,215.0

In [33]:
nhanes.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5703 entries, 0 to 5702
Data columns (total 33 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   SEQN      5703 non-null   float64
 1   SDDSRVYR  5703 non-null   float64
 2   RIDSTATR  5703 non-null   float64
 3   RIAGENDR  5703 non-null   float64
 4   RIDAGEYR  5703 non-null   float64
 5   RIDRETH1  5703 non-null   float64
 6   DMQMILIZ  5703 non-null   float64
 7   DMDBORN4  5703 non-null   float64
 8   DMDYRUSR  1140 non-null   float64
 9   DMDEDUC2  5449 non-null   float64
 10  DMDMARTZ  5448 non-null   float64
 11  DMDHHSIZ  5703 non-null   float64
 12  WTINT2YR  5703 non-null   float64
 13  WTMEC2YR  5703 non-null   float64
 14  ALQ111    4929 non-null   float64
 15  ALQ121    4429 non-null   float64
 16  ALQ130    3657 non-null   float64
 17  ALQ151    4409 non-null   float64
 18  ALQ170    2113 non-null   float64
 19  HIQ011    5703 non-null   float64
 20  HIQ032A   3037 non-null   float64
 21  HIQ032B   1977 non-null   float64
 22  HIQ032D   841 non-null    float64
 23  HIQ032F   238 non-null    float64
 24  HIQ032H   434 non-null    float64
 25  HIQ032I   225 non-null    float64
 26  HIQ210    5218 non-null   float64
 27  INDFMMPC  5229 non-null   float64
 28  INQ300    5230 non-null   float64
 29  IND310    2579 non-null   float64
 30  BPXOSY1   5510 non-null   float64
 31  BPXODI1   5510 non-null   float64
 32  LBXTC     5145 non-null   float64
dtypes: float64(33)
memory usage: 1.4 MB

### Task 2:

In [34]:
nhanes.describe()

,SEQN,SDDSRVYR,RIDSTATR,RIAGENDR,RIDAGEYR,RIDRETH1,DMQMILIZ,DMDBORN4,DMDYRUSR,DMDEDUC2,...,HIQ032F,HIQ032H,HIQ032I,HIQ210,INDFMMPC,INQ300,IND310,BPXOSY1,BPXODI1,LBXTC
count,5703.000000,5703.0,5703.0,5703.000000,5703.000000,5703.000000,5703.000000,5703.000000,1140.000000,5449.000000,...,238.0,434.0,225.0,5218.000000,5229.000000,5230.000000,2579.000000,5510.000000,5510.000000,5145.000000
mean,136349.344906,12.0,2.0,1.546204,52.334911,3.123619,1.912502,1.199895,6.900000,3.840154,...,6.0,8.0,9.0,1.966079,2.494358,1.727533,3.367584,122.599274,74.945554,186.921866
std,3434.441227,0.0,0.0,0.497904,18.352717,0.984967,0.282588,0.399956,13.346618,1.137708,...,0.0,0.0,0.0,0.375346,1.246655,1.269765,12.382223,18.512221,11.428117,42.602522
min,130379.000000,12.0,2.0,1.000000,18.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,6.0,8.0,9.0,1.000000,1.000000,1.000000,1.000000,73.000000,36.000000,62.000000
25%,133347.000000,12.0,2.0,1.000000,37.000000,3.000000,2.000000,1.000000,4.000000,3.000000,...,6.0,8.0,9.0,2.000000,2.000000,1.000000,1.000000,110.000000,67.000000,157.000000
50%,136383.000000,12.0,2.0,2.000000,56.000000,3.000000,2.000000,1.000000,6.000000,4.000000,...,6.0,8.0,9.0,2.000000,3.000000,2.000000,1.000000,120.000000,74.000000,184.000000
75%,139318.000000,12.0,2.0,2.000000,68.000000,3.000000,2.000000,1.000000,6.000000,5.000000,...,6.0,8.0,9.0,2.000000,3.000000,2.000000,2.000000,133.000000,82.000000,213.000000
max,142310.000000,12.0,2.0,2.000000,80.000000,5.000000,2.000000,2.000000,99.000000,9.000000,...,6.0,8.0,9.0,9.000000,9.000000,9.000000,99.000000,232.000000,142.000000,438.000000

In [35]:
missing = nhanes.isnull().sum()
missing

SEQN           0
SDDSRVYR       0
RIDSTATR       0
RIAGENDR       0
RIDAGEYR       0
RIDRETH1       0
DMQMILIZ       0
DMDBORN4       0
DMDYRUSR    4563
DMDEDUC2     254
DMDMARTZ     255
DMDHHSIZ       0
WTINT2YR       0
WTMEC2YR       0
ALQ111       774
ALQ121      1274
ALQ130      2046
ALQ151      1294
ALQ170      3590
HIQ011         0
HIQ032A     2666
HIQ032B     3726
HIQ032D     4862
HIQ032F     5465
HIQ032H     5269
HIQ032I     5478
HIQ210       485
INDFMMPC     474
INQ300       473
IND310      3124
BPXOSY1      193
BPXODI1      193
LBXTC        558
dtype: int64

In [36]:
missing_values_as_percent = (missing / len(nhanes) * 100).round(4)
missing_values_as_percent

SEQN         0.0000
SDDSRVYR     0.0000
RIDSTATR     0.0000
RIAGENDR     0.0000
RIDAGEYR     0.0000
RIDRETH1     0.0000
DMQMILIZ     0.0000
DMDBORN4     0.0000
DMDYRUSR    80.0105
DMDEDUC2     4.4538
DMDMARTZ     4.4713
DMDHHSIZ     0.0000
WTINT2YR     0.0000
WTMEC2YR     0.0000
ALQ111      13.5718
ALQ121      22.3391
ALQ130      35.8759
ALQ151      22.6898
ALQ170      62.9493
HIQ011       0.0000
HIQ032A     46.7473
HIQ032B     65.3340
HIQ032D     85.2534
HIQ032F     95.8268
HIQ032H     92.3900
HIQ032I     96.0547
HIQ210       8.5043
INDFMMPC     8.3114
INQ300       8.2939
IND310      54.7782
BPXOSY1      3.3842
BPXODI1      3.3842
LBXTC        9.7843
dtype: float64

In [37]:
nhanes.nunique()

SEQN        5703
SDDSRVYR       1
RIDSTATR       1
RIAGENDR       2
RIDAGEYR      63
RIDRETH1       5
DMQMILIZ       2
DMDBORN4       2
DMDYRUSR       8
DMDEDUC2       6
DMDMARTZ       5
DMDHHSIZ       7
WTINT2YR    5253
WTMEC2YR    5428
ALQ111         3
ALQ121        13
ALQ130        17
ALQ151         3
ALQ170        21
HIQ011         4
HIQ032A        3
HIQ032B        1
HIQ032D        1
HIQ032F        1
HIQ032H        1
HIQ032I        1
HIQ210         4
INDFMMPC       5
INQ300         4
IND310         7
BPXOSY1      133
BPXODI1       88
LBXTC        257
dtype: int64

### Task 3:

In [38]:
# Create helper function to classify blood pressure for every row
def classify_bp(row):
    systolic_bp = row["BPXOSY1"]
    diastolic_bp = row["BPXODI1"]
    # Edge case where either systolic or diastolic are missing
    if pd.isna(systolic_bp) or pd.isna(diastolic_bp):
        return np.nan
    if systolic_bp < 120 and diastolic_bp < 80:
        return "normal"
    else:
        return "abnormal"

In [39]:
# Pass in function to every row to classify and label the new BP column
nhanes['BP'] = nhanes.apply(classify_bp, axis=1)
nhanes['BP'].value_counts()

BP
abnormal    3119
normal      2391
Name: count, dtype: int64

In [40]:
nhanes['BP']

0         normal
1       abnormal
2         normal
3       abnormal
4         normal
          ...
5698      normal
5699    abnormal
5700    abnormal
5701    abnormal
5702    abnormal
Name: BP, Length: 5703, dtype: object

In [41]:
def classify_cholesterol(value):
    if pd.isna(value):
        return np.nan
    if value < 200:
        return "normal"
    elif value <= 239:
        return "borderline"
    else:
        return "high"

In [42]:
nhanes["CHOL"] = nhanes["LBXTC"].apply(classify_cholesterol)
nhanes["CHOL"].value_counts()

CHOL
normal        3325
borderline    1257
high           563
Name: count, dtype: int64

In [43]:
nhanes = nhanes.drop(columns=['BPXOSY1', 'BPXODI1', 'LBXTC'])

In [44]:
nhanes[["BP", "CHOL"]].head()

         BP        CHOL
0    normal  borderline
1  abnormal      normal
2    normal      normal
3  abnormal  borderline
4    normal  borderline

### Task 4:

In [45]:
from sklearn.model_selection import train_test_split

bp_ernazarov = nhanes.copy()
chol_ernazarov = nhanes.copy()

In [46]:
bp_training_ernazarov, bp_test_ernazarov = train_test_split(bp_ernazarov, train_size=0.8, test_size=0.2, random_state=42)

In [47]:
chol_training_ernazarov, chol_test_ernazarov = train_test_split(chol_ernazarov, train_size=0.8, test_size=0.2, random_state=42)

In [48]:
bp_training_ernazarov.head()

,SEQN,SDDSRVYR,RIDSTATR,RIAGENDR,RIDAGEYR,RIDRETH1,DMQMILIZ,DMDBORN4,DMDYRUSR,DMDEDUC2,...,HIQ032D,HIQ032F,HIQ032H,HIQ032I,HIQ210,INDFMMPC,INQ300,IND310,BP,CHOL
1892,132398.0,12.0,2.0,1.0,31.0,2.0,2.0,2.0,2.0,5.0,...,NaN,NaN,NaN,NaN,NaN,1.0,2.0,4.0,normal,borderline
3196,134479.0,12.0,2.0,1.0,55.0,3.0,2.0,1.0,NaN,5.0,...,NaN,NaN,NaN,NaN,NaN,7.0,2.0,1.0,normal,normal
3443,139895.0,12.0,2.0,1.0,73.0,2.0,2.0,2.0,6.0,5.0,...,4.0,NaN,NaN,NaN,2.0,2.0,2.0,4.0,normal,normal
4993,132502.0,12.0,2.0,1.0,69.0,2.0,1.0,1.0,NaN,4.0,...,NaN,NaN,NaN,NaN,2.0,3.0,2.0,3.0,abnormal,normal
1071,133635.0,12.0,2.0,1.0,44.0,3.0,2.0,1.0,NaN,4.0,...,NaN,NaN,NaN,NaN,2.0,3.0,1.0,NaN,normal,borderline

In [49]:
chol_training_ernazarov.head()

,SEQN,SDDSRVYR,RIDSTATR,RIAGENDR,RIDAGEYR,RIDRETH1,DMQMILIZ,DMDBORN4,DMDYRUSR,DMDEDUC2,...,HIQ032D,HIQ032F,HIQ032H,HIQ032I,HIQ210,INDFMMPC,INQ300,IND310,BP,CHOL
1892,132398.0,12.0,2.0,1.0,31.0,2.0,2.0,2.0,2.0,5.0,...,NaN,NaN,NaN,NaN,NaN,1.0,2.0,4.0,normal,borderline
3196,134479.0,12.0,2.0,1.0,55.0,3.0,2.0,1.0,NaN,5.0,...,NaN,NaN,NaN,NaN,NaN,7.0,2.0,1.0,normal,normal
3443,139895.0,12.0,2.0,1.0,73.0,2.0,2.0,2.0,6.0,5.0,...,4.0,NaN,NaN,NaN,2.0,2.0,2.0,4.0,normal,normal
4993,132502.0,12.0,2.0,1.0,69.0,2.0,1.0,1.0,NaN,4.0,...,NaN,NaN,NaN,NaN,2.0,3.0,2.0,3.0,abnormal,normal
1071,133635.0,12.0,2.0,1.0,44.0,3.0,2.0,1.0,NaN,4.0,...,NaN,NaN,NaN,NaN,2.0,3.0,1.0,NaN,normal,borderline

### Task 5:

In [50]:
def pre_clean_data(df):
    
    # HIQ032 checkbox columns: NaN means "not checked" → 0, any value → 1
    hiq_cols = ['HIQ032A', 'HIQ032B', 'HIQ032D', 'HIQ032F', 'HIQ032H', 'HIQ032I']
    for col in hiq_cols:
        df[col] = df[col].notna().astype(int)
        
    # Remap binary 1/2 features to 1/0 (1=Yes stays 1, 2=No becomes 0)
    binary_remap = ['RIAGENDR', 'DMQMILIZ', 'DMDBORN4', 'ALQ111', 'ALQ151','HIQ011', 'HIQ210', 'INQ300']
    for col in binary_remap:
        df[col] = df[col].map({1: 1, 2: 0})

    # Drop non-predictive columns
    df = df.drop(columns=['SEQN', 'SDDSRVYR', 'RIDSTATR'])
    
    return df

In [51]:
bp_clean = pre_clean_data(bp_training_ernazarov)
chol_clean = pre_clean_data(chol_training_ernazarov)

In [54]:
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.impute import SimpleImputer

nominal_cols = ['RIDRETH1', 'DMDMARTZ']

nominal_pipeline = Pipeline(steps=[
    ('impute', SimpleImputer(strategy='most_frequent')),
    ('onehot', OneHotEncoder(handle_unknown='ignore', sparse_output=False))
])

preprocessor_b = ColumnTransformer(
    transformers=[
        ('nominal', nominal_pipeline, nominal_cols)
])

preprocessor_c = ColumnTransformer(
    transformers=[
        ('nominal', nominal_pipeline, nominal_cols)
])

plineb = Pipeline(steps=[('preprocessor', preprocessor_b)])
plinec = Pipeline(steps=[('preprocessor', preprocessor_c)])

In [55]:
bp_X = bp_clean.drop(columns=['BP', 'CHOL'])
bp_y = bp_clean['BP']
bp_transformed = plineb.fit_transform(bp_X)

bp_feature_names = plineb.named_steps['preprocessor'].get_feature_names_out()
bp_transformed_df = pd.DataFrame(bp_transformed, columns=bp_feature_names)
bp_transformed_df.tail()

,nominal__RIDRETH1_1.0,nominal__RIDRETH1_2.0,nominal__RIDRETH1_3.0,nominal__RIDRETH1_4.0,nominal__RIDRETH1_5.0,nominal__DMDMARTZ_1.0,nominal__DMDMARTZ_2.0,nominal__DMDMARTZ_3.0,nominal__DMDMARTZ_77.0,nominal__DMDMARTZ_99.0
4557,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0
4558,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0
4559,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
4560,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
4561,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0

In [56]:
chol_X = chol_clean.drop(columns=['BP', 'CHOL'])
chol_y = chol_clean['CHOL']

chol_transformed = plinec.fit_transform(chol_X)

chol_feature_names = plinec.named_steps['preprocessor'].get_feature_names_out()
chol_transformed_df = pd.DataFrame(chol_transformed, columns=chol_feature_names)
chol_transformed_df.tail()

,nominal__RIDRETH1_1.0,nominal__RIDRETH1_2.0,nominal__RIDRETH1_3.0,nominal__RIDRETH1_4.0,nominal__RIDRETH1_5.0,nominal__DMDMARTZ_1.0,nominal__DMDMARTZ_2.0,nominal__DMDMARTZ_3.0,nominal__DMDMARTZ_77.0,nominal__DMDMARTZ_99.0
4557,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0
4558,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0
4559,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
4560,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
4561,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0