# Project Notebook
## Step 1: Data Preparation

### Task 1:

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

nhanes = pd.read_csv('nhanes.csv')
nhanes.head()

,SEQN,SDDSRVYR,RIDSTATR,RIAGENDR,RIDAGEYR,RIDRETH1,DMQMILIZ,DMDBORN4,DMDYRUSR,DMDEDUC2,...,HIQ032F,HIQ032H,HIQ032I,HIQ210,INDFMMPC,INQ300,IND310,BPXOSY1,BPXODI1,LBXTC
0,132141.0,12.0,2.0,2.0,56.0,4.0,2.0,1.0,NaN,5.0,...,NaN,NaN,NaN,2.0,3.0,1.0,NaN,115.0,70.0,205.0
1,136977.0,12.0,2.0,1.0,29.0,3.0,2.0,2.0,2.0,5.0,...,NaN,NaN,NaN,2.0,3.0,2.0,2.0,125.0,71.0,193.0
2,134280.0,12.0,2.0,2.0,25.0,3.0,2.0,1.0,NaN,5.0,...,NaN,NaN,NaN,2.0,3.0,1.0,NaN,111.0,69.0,87.0
3,132522.0,12.0,2.0,2.0,64.0,3.0,2.0,1.0,NaN,4.0,...,NaN,NaN,NaN,2.0,NaN,NaN,NaN,113.0,90.0,215.0
4,138725.0,12.0,2.0,2.0,28.0,3.0,2.0,1.0,NaN,5.0,...,NaN,NaN,NaN,2.0,3.0,1.0,NaN,114.0,69.0,215.0

In [2]:
nhanes.info()

<class 'pandas.DataFrame'>
RangeIndex: 5703 entries, 0 to 5702
Data columns (total 33 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   SEQN      5703 non-null   float64
 1   SDDSRVYR  5703 non-null   float64
 2   RIDSTATR  5703 non-null   float64
 3   RIAGENDR  5703 non-null   float64
 4   RIDAGEYR  5703 non-null   float64
 5   RIDRETH1  5703 non-null   float64
 6   DMQMILIZ  5703 non-null   float64
 7   DMDBORN4  5703 non-null   float64
 8   DMDYRUSR  1140 non-null   float64
 9   DMDEDUC2  5449 non-null   float64
 10  DMDMARTZ  5448 non-null   float64
 11  DMDHHSIZ  5703 non-null   float64
 12  WTINT2YR  5703 non-null   float64
 13  WTMEC2YR  5703 non-null   float64
 14  ALQ111    4929 non-null   float64
 15  ALQ121    4429 non-null   float64
 16  ALQ130    3657 non-null   float64
 17  ALQ151    4409 non-null   float64
 18  ALQ170    2113 non-null   float64
 19  HIQ011    5703 non-null   float64
 20  HIQ032A   3037 non-null   float64
 21  HIQ032B   1977 non-null   float64
 22  HIQ032D   841 non-null    float64
 23  HIQ032F   238 non-null    float64
 24  HIQ032H   434 non-null    float64
 25  HIQ032I   225 non-null    float64
 26  HIQ210    5218 non-null   float64
 27  INDFMMPC  5229 non-null   float64
 28  INQ300    5230 non-null   float64
 29  IND310    2579 non-null   float64
 30  BPXOSY1   5510 non-null   float64
 31  BPXODI1   5510 non-null   float64
 32  LBXTC     5145 non-null   float64
dtypes: float64(33)
memory usage: 1.4 MB

### Task 2:

In [3]:
nhanes.describe()

,SEQN,SDDSRVYR,RIDSTATR,RIAGENDR,RIDAGEYR,RIDRETH1,DMQMILIZ,DMDBORN4,DMDYRUSR,DMDEDUC2,...,HIQ032F,HIQ032H,HIQ032I,HIQ210,INDFMMPC,INQ300,IND310,BPXOSY1,BPXODI1,LBXTC
count,5703.000000,5703.0,5703.0,5703.000000,5703.000000,5703.000000,5703.000000,5703.000000,1140.000000,5449.000000,...,238.0,434.0,225.0,5218.000000,5229.000000,5230.000000,2579.000000,5510.000000,5510.000000,5145.000000
mean,136349.344906,12.0,2.0,1.546204,52.334911,3.123619,1.912502,1.199895,6.900000,3.840154,...,6.0,8.0,9.0,1.966079,2.494358,1.727533,3.367584,122.599274,74.945554,186.921866
std,3434.441227,0.0,0.0,0.497904,18.352717,0.984967,0.282588,0.399956,13.346618,1.137708,...,0.0,0.0,0.0,0.375346,1.246655,1.269765,12.382223,18.512221,11.428117,42.602522
min,130379.000000,12.0,2.0,1.000000,18.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,6.0,8.0,9.0,1.000000,1.000000,1.000000,1.000000,73.000000,36.000000,62.000000
25%,133347.000000,12.0,2.0,1.000000,37.000000,3.000000,2.000000,1.000000,4.000000,3.000000,...,6.0,8.0,9.0,2.000000,2.000000,1.000000,1.000000,110.000000,67.000000,157.000000
50%,136383.000000,12.0,2.0,2.000000,56.000000,3.000000,2.000000,1.000000,6.000000,4.000000,...,6.0,8.0,9.0,2.000000,3.000000,2.000000,1.000000,120.000000,74.000000,184.000000
75%,139318.000000,12.0,2.0,2.000000,68.000000,3.000000,2.000000,1.000000,6.000000,5.000000,...,6.0,8.0,9.0,2.000000,3.000000,2.000000,2.000000,133.000000,82.000000,213.000000
max,142310.000000,12.0,2.0,2.000000,80.000000,5.000000,2.000000,2.000000,99.000000,9.000000,...,6.0,8.0,9.0,9.000000,9.000000,9.000000,99.000000,232.000000,142.000000,438.000000

In [4]:
missing = nhanes.isnull().sum()
missing

SEQN           0
SDDSRVYR       0
RIDSTATR       0
RIAGENDR       0
RIDAGEYR       0
RIDRETH1       0
DMQMILIZ       0
DMDBORN4       0
DMDYRUSR    4563
DMDEDUC2     254
DMDMARTZ     255
DMDHHSIZ       0
WTINT2YR       0
WTMEC2YR       0
ALQ111       774
ALQ121      1274
ALQ130      2046
ALQ151      1294
ALQ170      3590
HIQ011         0
HIQ032A     2666
HIQ032B     3726
HIQ032D     4862
HIQ032F     5465
HIQ032H     5269
HIQ032I     5478
HIQ210       485
INDFMMPC     474
INQ300       473
IND310      3124
BPXOSY1      193
BPXODI1      193
LBXTC        558
dtype: int64

In [5]:
missing_values_as_percent = (missing / len(nhanes) * 100).round(4)
missing_values_as_percent

SEQN         0.0000
SDDSRVYR     0.0000
RIDSTATR     0.0000
RIAGENDR     0.0000
RIDAGEYR     0.0000
RIDRETH1     0.0000
DMQMILIZ     0.0000
DMDBORN4     0.0000
DMDYRUSR    80.0105
DMDEDUC2     4.4538
DMDMARTZ     4.4713
DMDHHSIZ     0.0000
WTINT2YR     0.0000
WTMEC2YR     0.0000
ALQ111      13.5718
ALQ121      22.3391
ALQ130      35.8759
ALQ151      22.6898
ALQ170      62.9493
HIQ011       0.0000
HIQ032A     46.7473
HIQ032B     65.3340
HIQ032D     85.2534
HIQ032F     95.8268
HIQ032H     92.3900
HIQ032I     96.0547
HIQ210       8.5043
INDFMMPC     8.3114
INQ300       8.2939
IND310      54.7782
BPXOSY1      3.3842
BPXODI1      3.3842
LBXTC        9.7843
dtype: float64

In [6]:
nhanes.nunique()

SEQN        5703
SDDSRVYR       1
RIDSTATR       1
RIAGENDR       2
RIDAGEYR      63
RIDRETH1       5
DMQMILIZ       2
DMDBORN4       2
DMDYRUSR       8
DMDEDUC2       6
DMDMARTZ       5
DMDHHSIZ       7
WTINT2YR    5253
WTMEC2YR    5428
ALQ111         3
ALQ121        13
ALQ130        17
ALQ151         3
ALQ170        21
HIQ011         4
HIQ032A        3
HIQ032B        1
HIQ032D        1
HIQ032F        1
HIQ032H        1
HIQ032I        1
HIQ210         4
INDFMMPC       5
INQ300         4
IND310         7
BPXOSY1      133
BPXODI1       88
LBXTC        257
dtype: int64

### Task 3:

In [7]:
# Create helper function to classify blood pressure for every row
def classify_bp(row):
    systolic_bp = row["BPXOSY1"]
    diastolic_bp = row["BPXODI1"]
    # Edge case where either systolic or diastolic are missing
    if pd.isna(systolic_bp) or pd.isna(diastolic_bp):
        return np.nan
    if systolic_bp < 120 and diastolic_bp < 80:
        return "normal"
    else:
        return "abnormal"

In [8]:
# Pass in function to every row to classify and label the new BP column
nhanes['BP'] = nhanes.apply(classify_bp, axis=1)
nhanes['BP'].value_counts()

BP
abnormal    3119
normal      2391
Name: count, dtype: int64

In [9]:
nhanes['BP']

0         normal
1       abnormal
2         normal
3       abnormal
4         normal
          ...
5698      normal
5699    abnormal
5700    abnormal
5701    abnormal
5702    abnormal
Name: BP, Length: 5703, dtype: str

In [10]:
def classify_cholesterol(value):
    if pd.isna(value):
        return np.nan
    if value < 200:
        return "normal"
    elif value <= 239:
        return "borderline"
    else:
        return "high"

In [11]:
nhanes["CHOL"] = nhanes["LBXTC"].apply(classify_cholesterol)
nhanes["CHOL"].value_counts()

CHOL
normal        3325
borderline    1257
high           563
Name: count, dtype: int64

In [12]:
nhanes = nhanes.drop(columns=['BPXOSY1', 'BPXODI1', 'LBXTC'])

In [13]:
nhanes[["BP", "CHOL"]].head()

         BP        CHOL
0    normal  borderline
1  abnormal      normal
2    normal      normal
3  abnormal  borderline
4    normal  borderline

### Task 4:

In [14]:
from sklearn.model_selection import train_test_split

bp_ernazarov = nhanes.copy()
chol_ernazarov = nhanes.copy()

In [15]:
bp_training_ernazarov, bp_test_ernazarov = train_test_split(bp_ernazarov, train_size=0.8, test_size=0.2, random_state=42)

In [16]:
chol_training_ernazarov, chol_test_ernazarov = train_test_split(chol_ernazarov, train_size=0.8, test_size=0.2, random_state=42)

In [17]:
bp_training_ernazarov.head()

,SEQN,SDDSRVYR,RIDSTATR,RIAGENDR,RIDAGEYR,RIDRETH1,DMQMILIZ,DMDBORN4,DMDYRUSR,DMDEDUC2,...,HIQ032D,HIQ032F,HIQ032H,HIQ032I,HIQ210,INDFMMPC,INQ300,IND310,BP,CHOL
1892,132398.0,12.0,2.0,1.0,31.0,2.0,2.0,2.0,2.0,5.0,...,NaN,NaN,NaN,NaN,NaN,1.0,2.0,4.0,normal,borderline
3196,134479.0,12.0,2.0,1.0,55.0,3.0,2.0,1.0,NaN,5.0,...,NaN,NaN,NaN,NaN,NaN,7.0,2.0,1.0,normal,normal
3443,139895.0,12.0,2.0,1.0,73.0,2.0,2.0,2.0,6.0,5.0,...,4.0,NaN,NaN,NaN,2.0,2.0,2.0,4.0,normal,normal
4993,132502.0,12.0,2.0,1.0,69.0,2.0,1.0,1.0,NaN,4.0,...,NaN,NaN,NaN,NaN,2.0,3.0,2.0,3.0,abnormal,normal
1071,133635.0,12.0,2.0,1.0,44.0,3.0,2.0,1.0,NaN,4.0,...,NaN,NaN,NaN,NaN,2.0,3.0,1.0,NaN,normal,borderline

In [18]:
chol_training_ernazarov.head()

,SEQN,SDDSRVYR,RIDSTATR,RIAGENDR,RIDAGEYR,RIDRETH1,DMQMILIZ,DMDBORN4,DMDYRUSR,DMDEDUC2,...,HIQ032D,HIQ032F,HIQ032H,HIQ032I,HIQ210,INDFMMPC,INQ300,IND310,BP,CHOL
1892,132398.0,12.0,2.0,1.0,31.0,2.0,2.0,2.0,2.0,5.0,...,NaN,NaN,NaN,NaN,NaN,1.0,2.0,4.0,normal,borderline
3196,134479.0,12.0,2.0,1.0,55.0,3.0,2.0,1.0,NaN,5.0,...,NaN,NaN,NaN,NaN,NaN,7.0,2.0,1.0,normal,normal
3443,139895.0,12.0,2.0,1.0,73.0,2.0,2.0,2.0,6.0,5.0,...,4.0,NaN,NaN,NaN,2.0,2.0,2.0,4.0,normal,normal
4993,132502.0,12.0,2.0,1.0,69.0,2.0,1.0,1.0,NaN,4.0,...,NaN,NaN,NaN,NaN,2.0,3.0,2.0,3.0,abnormal,normal
1071,133635.0,12.0,2.0,1.0,44.0,3.0,2.0,1.0,NaN,4.0,...,NaN,NaN,NaN,NaN,2.0,3.0,1.0,NaN,normal,borderline

### Task 5:

In [19]:
def pre_clean_data(df):
    
    # HIQ032 checkbox columns: NaN means "not checked" → 0, any value → 1
    hiq_cols = ['HIQ032A', 'HIQ032B', 'HIQ032D', 'HIQ032F', 'HIQ032H', 'HIQ032I']
    for col in hiq_cols:
        df[col] = df[col].notna().astype(int)
        
    # Remap binary 1/2 features to 1/0 (1=Yes stays 1, 2=No becomes 0)
    binary_remap = ['RIAGENDR', 'DMQMILIZ', 'DMDBORN4', 'ALQ111', 'ALQ151','HIQ011', 'HIQ210', 'INQ300']
    for col in binary_remap:
        df[col] = df[col].map({1: 1, 2: 0})

    # Drop non-predictive columns
    df = df.drop(columns=['SEQN', 'SDDSRVYR', 'RIDSTATR'])
    
    return df

In [20]:
bp_clean = pre_clean_data(bp_training_ernazarov)
chol_clean = pre_clean_data(chol_training_ernazarov)

In [21]:
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.impute import SimpleImputer

nominal_cols = ['RIDRETH1', 'DMDMARTZ']
numeric_cols = [col for col in bp_clean.drop(columns=['BP', 'CHOL']).columns if col not in nominal_cols]

numeric_pipeline = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='median')),
    ('scaler', StandardScaler())
])

nominal_pipeline = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='most_frequent')),
    ('onehot', OneHotEncoder(handle_unknown='ignore', sparse_output=False))
])

preprocessor_b = ColumnTransformer(transformers=[
    ('numeric', numeric_pipeline, numeric_cols),
    ('nominal', nominal_pipeline, nominal_cols)
])

preprocessor_c = ColumnTransformer(transformers=[
    ('numeric', numeric_pipeline, numeric_cols),
    ('nominal', nominal_pipeline, nominal_cols)
])

plineb = Pipeline(steps=[('preprocessor', preprocessor_b)])
plinec = Pipeline(steps=[('preprocessor', preprocessor_c)])

In [22]:
bp_X = bp_clean.drop(columns=['BP', 'CHOL'])
bp_y = bp_clean['BP']

bp_mask = bp_y.notna()
bp_X = bp_X[bp_mask]
bp_y = bp_y[bp_mask]

bp_transformed = plineb.fit_transform(bp_X)

bp_feature_names = plineb.named_steps['preprocessor'].get_feature_names_out()
bp_transformed_df = pd.DataFrame(bp_transformed, columns=bp_feature_names)
bp_transformed_df.tail()

,numeric__RIAGENDR,numeric__RIDAGEYR,numeric__DMQMILIZ,numeric__DMDBORN4,numeric__DMDYRUSR,numeric__DMDEDUC2,numeric__DMDHHSIZ,numeric__WTINT2YR,numeric__WTMEC2YR,numeric__ALQ111,...,nominal__RIDRETH1_1.0,nominal__RIDRETH1_2.0,nominal__RIDRETH1_3.0,nominal__RIDRETH1_4.0,nominal__RIDRETH1_5.0,nominal__DMDMARTZ_1.0,nominal__DMDMARTZ_2.0,nominal__DMDMARTZ_3.0,nominal__DMDMARTZ_77.0,nominal__DMDMARTZ_99.0
4402,1.085563,0.635144,-0.311588,0.49702,-0.029282,-0.776014,-0.402627,-0.434341,-0.365662,-3.182576,...,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0
4403,-0.921181,0.525506,-0.311588,0.49702,-0.029282,-0.776014,-1.082988,-0.190383,-0.200801,0.314211,...,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0
4404,1.085563,0.635144,3.209361,0.49702,-0.029282,-0.776014,-1.082988,-0.015846,0.148818,0.314211,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
4405,1.085563,0.470686,-0.311588,0.49702,-0.029282,1.031063,-0.402627,-0.789554,-0.870362,0.314211,...,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
4406,1.085563,0.689964,-0.311588,0.49702,-0.029282,0.127525,-0.402627,0.804346,0.574828,0.314211,...,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0

In [23]:
chol_X = chol_clean.drop(columns=['BP', 'CHOL'])
chol_y = chol_clean['CHOL']

chol_mask = chol_y.notna()
chol_X = chol_X[chol_mask]
chol_y = chol_y[chol_mask]

chol_transformed = plinec.fit_transform(chol_X)

chol_feature_names = plinec.named_steps['preprocessor'].get_feature_names_out()
chol_transformed_df = pd.DataFrame(chol_transformed, columns=chol_feature_names)
chol_transformed_df.tail()

,numeric__RIAGENDR,numeric__RIDAGEYR,numeric__DMQMILIZ,numeric__DMDBORN4,numeric__DMDYRUSR,numeric__DMDEDUC2,numeric__DMDHHSIZ,numeric__WTINT2YR,numeric__WTMEC2YR,numeric__ALQ111,...,nominal__RIDRETH1_1.0,nominal__RIDRETH1_2.0,nominal__RIDRETH1_3.0,nominal__RIDRETH1_4.0,nominal__RIDRETH1_5.0,nominal__DMDMARTZ_1.0,nominal__DMDMARTZ_2.0,nominal__DMDMARTZ_3.0,nominal__DMDMARTZ_77.0,nominal__DMDMARTZ_99.0
4110,1.077082,0.629646,-0.313855,0.503415,-0.025529,-0.789971,-0.414967,-0.438636,-0.370772,-3.229637,...,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0
4111,-0.928435,0.519234,-0.313855,0.503415,-0.025529,-0.789971,-1.090439,-0.197158,-0.207062,0.309632,...,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0
4112,1.077082,0.629646,3.186183,0.503415,-0.025529,-0.789971,-1.090439,-0.024396,0.140116,0.309632,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
4113,1.077082,0.464028,-0.313855,0.503415,-0.025529,1.013486,-0.414967,-0.790239,-0.871950,0.309632,...,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
4114,1.077082,0.684852,-0.313855,0.503415,-0.025529,0.111757,-0.414967,0.787459,0.563153,0.309632,...,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0

## Step 2: Choosing some learners

### Task 6:

### Note:
After running the algorithms with little-to-no hyperparameter tuning or default configurations, I decided to try a hyperparameter tuning method such as `GridSearch` to find the ideal hyperparamters for all of the algorithms to see if we could bump up our scores by a little bit.

In [24]:
from sklearn.model_selection import GridSearchCV

param_grids = {
    'Decision Stump': {
        'classifier__criterion': ['gini', 'entropy'],
        'classifier__splitter': ['best', 'random']
    },
    'Decision Tree': {
        'classifier__max_depth': [3, 5, 10, 15, 20, None],
        'classifier__criterion': ['gini', 'entropy'],
        'classifier__min_samples_split': [2, 5, 10],
        'classifier__min_samples_leaf': [1, 2, 5]
    },
    'Random Forest': {
        'classifier__n_estimators': [100, 500, 1000],
        'classifier__max_depth': [5, 10, 20, None],
        'classifier__min_samples_split': [2, 5, 10],
        'classifier__min_samples_leaf': [1, 2, 5]
    },
    'Gradient Boosting': {
        'classifier__n_estimators': [100, 500, 1000],
        'classifier__learning_rate': [0.01, 0.1, 0.2],
        'classifier__max_depth': [3, 5, 7],
        'classifier__min_samples_split': [2, 5, 10]
    },
    'Support Vector Machine': {
        'classifier__C': [0.1, 1, 10, 100],
        'classifier__kernel': ['rbf', 'poly'],
        'classifier__gamma': ['scale', 'auto']
    },
    'Naive Bayes': {
        'classifier__var_smoothing': [1e-9, 1e-8, 1e-7, 1e-6, 1e-5]
    },
    'Logistic Regression': {
        'classifier__C': [0.01, 0.1, 1, 10, 100],
        'classifier__solver': ['lbfgs', 'saga'],
        'classifier__max_iter': [1000, 2000]
    },
    'Stochastic Gradient Descent': {
        'classifier__loss': ['log_loss', 'modified_huber'],
        'classifier__alpha': [0.0001, 0.001, 0.01],
        'classifier__penalty': ['l2', 'l1', 'elasticnet'],
        'classifier__max_iter': [1000, 2000]
    }
}

In [25]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.svm import SVC
from sklearn.naive_bayes import GaussianNB
from sklearn.linear_model import LogisticRegression, SGDClassifier
from sklearn.model_selection import cross_validate
from scipy.stats import f_oneway

algorithms = {
    "Decision Stump": DecisionTreeClassifier(max_depth=1, random_state=42),
    "Decision Tree": DecisionTreeClassifier(random_state=42),
    "Random Forest": RandomForestClassifier(n_estimators=100, random_state=42),
    "Gradient Boosting": GradientBoostingClassifier(n_estimators=100, random_state=42),
    "Support Vector Machine": SVC(kernel='rbf', random_state=42),
    "Naive Bayes": GaussianNB(),
    "Logistic Regression": LogisticRegression(max_iter=1000, random_state=42),
    "Stochastic Gradient Descent": SGDClassifier(random_state=42)
}

scoring = ['accuracy', 'f1_weighted', 'recall_weighted']

In [26]:
bp_best_hyperparameters = {}

for name, clf in algorithms.items():
    pipe = Pipeline([
        ('preprocessor', preprocessor_b),
        ('classifier', clf)
    ])
    
    grid_search = GridSearchCV(
        pipe,
        param_grids[name],
        cv=5,
        scoring='f1_weighted',
        n_jobs=-1
    )
    grid_search.fit(bp_X, bp_y)
    
    bp_best_hyperparameters[name] = {
        'best_params': grid_search.best_params_,
        'best_score': round(grid_search.best_score_, 4)
    }
    print(f"{name}: {grid_search.best_score_:.4f} - {grid_search.best_params_}")

pd.DataFrame({name: info for name, info in bp_best_hyperparameters.items()}).T

Decision Stump: 0.6470 - {'classifier__criterion': 'gini', 'classifier__splitter': 'best'}
Decision Tree: 0.6592 - {'classifier__criterion': 'gini', 'classifier__max_depth': 3, 'classifier__min_samples_leaf': 1, 'classifier__min_samples_split': 2}
Random Forest: 0.6558 - {'classifier__max_depth': 10, 'classifier__min_samples_leaf': 2, 'classifier__min_samples_split': 10, 'classifier__n_estimators': 500}
Gradient Boosting: 0.6548 - {'classifier__learning_rate': 0.01, 'classifier__max_depth': 3, 'classifier__min_samples_split': 2, 'classifier__n_estimators': 500}
Support Vector Machine: 0.6427 - {'classifier__C': 1, 'classifier__gamma': 'scale', 'classifier__kernel': 'rbf'}
Naive Bayes: 0.5488 - {'classifier__var_smoothing': 1e-05}
Logistic Regression: 0.6611 - {'classifier__C': 1, 'classifier__max_iter': 1000, 'classifier__solver': 'lbfgs'}
Stochastic Gradient Descent: 0.6612 - {'classifier__alpha': 0.01, 'classifier__loss': 'log_loss', 'classifier__max_iter': 1000, 'classifier__penalty': 'l1'}

,best_params,best_score
Decision Stump,"{'classifier__criterion': 'gini', 'classifier_...",0.647
Decision Tree,"{'classifier__criterion': 'gini', 'classifier_...",0.6592
Random Forest,"{'classifier__max_depth': 10, 'classifier__min...",0.6558
Gradient Boosting,"{'classifier__learning_rate': 0.01, 'classifie...",0.6548
Support Vector Machine,"{'classifier__C': 1, 'classifier__gamma': 'sca...",0.6427
Naive Bayes,{'classifier__var_smoothing': 1e-05},0.5488
Logistic Regression,"{'classifier__C': 1, 'classifier__max_iter': 1...",0.6611
Stochastic Gradient Descent,"{'classifier__alpha': 0.01, 'classifier__loss'...",0.6612

In [27]:
bp_algorithms = {
    'Decision Stump': DecisionTreeClassifier(max_depth=1, criterion='gini', splitter='best', random_state=42),
    'Decision Tree': DecisionTreeClassifier(criterion='gini', max_depth=3, min_samples_leaf=1, min_samples_split=2, random_state=42),
    'Random Forest': RandomForestClassifier(max_depth=10, min_samples_leaf=2, min_samples_split=10, n_estimators=500, random_state=42),
    'Gradient Boosting': GradientBoostingClassifier(learning_rate=0.01, max_depth=3, min_samples_split=2, n_estimators=500, random_state=42),
    'Support Vector Machine': SVC(C=1, gamma='scale', kernel='rbf', random_state=42),
    'Naive Bayes': GaussianNB(var_smoothing=1e-05),
    'Logistic Regression': LogisticRegression(C=1, max_iter=1000, solver='lbfgs', random_state=42),
    'Stochastic Gradient Descent': SGDClassifier(alpha=0.01, loss='log_loss', max_iter=1000, penalty='l1', random_state=42)
}

In [28]:
bp_cv_results = {}

for name, model in bp_algorithms.items():
    pipeline = Pipeline(
        steps=[
            ('preprocessor', preprocessor_b), 
            ('classifier', model)
        ])
    cv_results = cross_validate(pipeline, bp_X, bp_y, cv=10, scoring=scoring)
    bp_cv_results[name] = cv_results
    
bp_cv_results

{'Decision Stump': {'fit_time': array([0.02906203, 0.03005886, 0.02304983, 0.02252913, 0.02612972,
         0.01703715, 0.01754236, 0.01923943, 0.01701808, 0.0175271 ]),
  'score_time': array([0.01903772, 0.01401448, 0.01502228, 0.01652217, 0.01051044,
         0.01001215, 0.01151752, 0.00850368, 0.00935698, 0.01003695]),
  'test_accuracy': array([0.67120181, 0.64172336, 0.63718821, 0.65759637, 0.69160998,
         0.6553288 , 0.65306122, 0.65      , 0.62727273, 0.64545455]),
  'test_f1_weighted': array([0.66986637, 0.63871615, 0.63245973, 0.64642488, 0.68592295,
         0.65235749, 0.64726412, 0.64123775, 0.62324463, 0.6365785 ]),
  'test_recall_weighted': array([0.67120181, 0.64172336, 0.63718821, 0.65759637, 0.69160998,
         0.6553288 , 0.65306122, 0.65      , 0.62727273, 0.64545455])},
 'Decision Tree': {'fit_time': array([0.02103496, 0.01951694, 0.01902485, 0.01852059, 0.01896262,
         0.02512956, 0.02305079, 0.02003121, 0.02025533, 0.02004743]),
  'score_time': array([0.00931787, 0.01002121, 0.01003981, 0.01001549, 0.00950623,
         0.0110147 , 0.01001549, 0.00901246, 0.01001501, 0.0100162 ]),
  'test_accuracy': array([0.68253968, 0.66666667, 0.66666667, 0.66893424, 0.70294785,
         0.68027211, 0.68027211, 0.66363636, 0.625     , 0.65454545]),
  'test_f1_weighted': array([0.67621696, 0.65817294, 0.65311721, 0.65050383, 0.6926852 ,
         0.67248716, 0.6690037 , 0.64865868, 0.61653281, 0.64138682]),
  'test_recall_weighted': array([0.68253968, 0.66666667, 0.66666667, 0.66893424, 0.70294785,
         0.68027211, 0.68027211, 0.66363636, 0.625     , 0.65454545])},
 'Random Forest': {'fit_time': array([1.33379602, 1.30207849, 1.33642626, 1.32181287, 1.32562423,
         1.35675025, 1.36140132, 1.31749654, 1.32860684, 1.29824901]),
  'score_time': array([0.06415439, 0.05199337, 0.05165124, 0.05159378, 0.05915451,
         0.05222678, 0.05113578, 0.05260301, 0.05115342, 0.05457091]),
  'test_accuracy': array([0.67800454, 0.65306122, 0.68027211, 0.69160998, 0.68480726,
         0.6553288 , 0.65759637, 0.66590909, 0.62272727, 0.64318182]),
  'test_f1_weighted': array([0.66839405, 0.64301839, 0.65953964, 0.67365835, 0.67391788,
         0.64482745, 0.64808937, 0.64746972, 0.61509143, 0.62995516]),
  'test_recall_weighted': array([0.67800454, 0.65306122, 0.68027211, 0.69160998, 0.68480726,
         0.6553288 , 0.65759637, 0.66590909, 0.62272727, 0.64318182])},
 'Gradient Boosting': {'fit_time': array([2.74318266, 2.69417095, 2.68382907, 2.78901553, 2.69684243,
         2.7130971 , 2.66697764, 2.66689897, 2.6734724 , 2.70464301]),
  'score_time': array([0.01151633, 0.01101327, 0.01201653, 0.0110147 , 0.0109973 ,
         0.01101398, 0.01101732, 0.01101542, 0.01208162, 0.01101208]),
  'test_accuracy': array([0.69387755, 0.66213152, 0.65986395, 0.68253968, 0.69614512,
         0.67573696, 0.67346939, 0.67045455, 0.625     , 0.65454545]),
  'test_f1_weighted': array([0.68754902, 0.65352223, 0.63638715, 0.6632332 , 0.6853492 ,
         0.66615385, 0.66411337, 0.65387848, 0.61769305, 0.64208835]),
  'test_recall_weighted': array([0.69387755, 0.66213152, 0.65986395, 0.68253968, 0.69614512,
         0.67573696, 0.67346939, 0.67045455, 0.625     , 0.65454545])},
 'Support Vector Machine': {'fit_time': array([0.41811156, 0.42111468, 0.41651869, 0.4255991 , 0.43160939,
         0.42782807, 0.40444899, 0.44154429, 0.4166553 , 0.43409419]),
  'score_time': array([0.08568764, 0.08708   , 0.09335423, 0.08661246, 0.08747101,
         0.08825278, 0.08397579, 0.08500099, 0.08347631, 0.08499551]),
  'test_accuracy': array([0.63945578, 0.63945578, 0.65759637, 0.67800454, 0.69160998,
         0.67120181, 0.66666667, 0.65      , 0.64090909, 0.63636364]),
  'test_f1_weighted': array([0.624026  , 0.62628678, 0.63722162, 0.65842224, 0.67667739,
         0.65895362, 0.65491875, 0.63441512, 0.62935827, 0.61674689]),
  'test_recall_weighted': array([0.63945578, 0.63945578, 0.65759637, 0.67800454, 0.69160998,
         0.67120181, 0.66666667, 0.65      , 0.64090909, 0.63636364])},
 'Naive Bayes': {'fit_time': array([0.01602316, 0.01550579, 0.01505804, 0.01452518, 0.01802945,
         0.01450872, 0.01506972, 0.021029  , 0.02018023, 0.01903701]),
  'score_time': array([0.00917983, 0.00901341, 0.0100162 , 0.00950742, 0.00834703,
         0.00901246, 0.01301384, 0.01252413, 0.01301217, 0.01001763]),
  'test_accuracy': array([0.59183673, 0.59637188, 0.58730159, 0.58049887, 0.58503401,
         0.60770975, 0.6031746 , 0.60454545, 0.61136364, 0.58636364]),
  'test_f1_weighted': array([0.50698316, 0.51939202, 0.52144746, 0.49204101, 0.48161618,
         0.54317551, 0.57807817, 0.5188232 , 0.5944895 , 0.47748386]),
  'test_recall_weighted': array([0.59183673, 0.59637188, 0.58730159, 0.58049887, 0.58503401,
         0.60770975, 0.6031746 , 0.60454545, 0.61136364, 0.58636364])},
 'Logistic Regression': {'fit_time': array([0.0290463 , 0.02503252, 0.02459908, 0.02403235, 0.02361441,
         0.02508044, 0.02329898, 0.0252676 , 0.01928568, 0.02453256]),
  'score_time': array([0.0125258 , 0.01001668, 0.00801635, 0.00932384, 0.01001549,
         0.00800991, 0.00950718, 0.00901341, 0.0100131 , 0.00900793]),
  'test_accuracy': array([0.69160998, 0.66213152, 0.65986395, 0.65759637, 0.70748299,
         0.65986395, 0.65759637, 0.65681818, 0.625     , 0.65681818]),
  'test_f1_weighted': array([0.68499733, 0.65661714, 0.64339418, 0.64508996, 0.69953014,
         0.65344615, 0.6528015 , 0.64673154, 0.6202649 , 0.64851202]),
  'test_recall_weighted': array([0.69160998, 0.66213152, 0.65986395, 0.65759637, 0.70748299,
         0.65986395, 0.65759637, 0.65681818, 0.625     , 0.65681818])},
 'Stochastic Gradient Descent': {'fit_time': array([0.02302551, 0.02259541, 0.02604413, 0.02268314, 0.02504444,
         0.02369118, 0.02108145, 0.02608705, 0.02202511, 0.02303529]),
  'score_time': array([0.00801349, 0.00951719, 0.0130837 , 0.01301455, 0.01025319,
         0.00940132, 0.00901341, 0.01001167, 0.00901222, 0.00901461]),
  'test_accuracy': array([0.6893424 , 0.65759637, 0.67573696, 0.66893424, 0.71428571,
         0.67120181, 0.68253968, 0.65454545, 0.62954545, 0.64318182]),
  'test_f1_weighted': array([0.68548669, 0.65200797, 0.66323388, 0.65582527, 0.70356147,
         0.66264296, 0.67507072, 0.64701921, 0.62575779, 0.63512515]),
  'test_recall_weighted': array([0.6893424 , 0.65759637, 0.67573696, 0.66893424, 0.71428571,
         0.67120181, 0.68253968, 0.65454545, 0.62954545, 0.64318182])}}

In [29]:
bp_summary = pd.DataFrame({
    name: {
        'Accuracy (mean)': cv['test_accuracy'].mean().round(4),
        'Accuracy (std)': cv['test_accuracy'].std().round(4),
        'F1 Weighted (mean)': cv['test_f1_weighted'].mean().round(4),
        'F1 Weighted (std)': cv['test_f1_weighted'].std().round(4),
        'Recall Weighted (mean)': cv['test_recall_weighted'].mean().round(4),
        'Recall Weighted (std)': cv['test_recall_weighted'].std().round(4),
    }
    for name, cv in bp_cv_results.items()
}).T # swap rows and columns

bp_summary

,Accuracy (mean),Accuracy (std),F1 Weighted (mean),F1 Weighted (std),Recall Weighted (mean),Recall Weighted (std)
Decision Stump,0.6530,0.0172,0.6474,0.0175,0.6530,0.0172
Decision Tree,0.6691,0.0194,0.6579,0.0201,0.6691,0.0194
Random Forest,0.6632,0.0201,0.6504,0.0181,0.6632,0.0201
Gradient Boosting,0.6694,0.0197,0.6570,0.0203,0.6694,0.0197
Support Vector Machine,0.6571,0.0181,0.6417,0.0184,0.6571,0.0181
Naive Bayes,0.5954,0.0102,0.5234,0.0369,0.5954,0.0102
Logistic Regression,0.6635,0.0210,0.6551,0.0211,0.6635,0.0210
Stochastic Gradient Descent,0.6687,0.0229,0.6606,0.0220,0.6687,0.0229

In [30]:
bp_accuracy_by_algorithm = [bp_cv_results[name]['test_accuracy'] for name in algorithms]

f_stat, p_value = f_oneway(*bp_accuracy_by_algorithm)
print(f"BP ANOVA: F-statistic = {f_stat:.4f}, p-value = {p_value:.6f}")

if p_value < 0.05: # H0 = null hypothesis, that all algorithms perform the same
    print("We reject H0: At least one algorithm performs significantly differently at 95% confidence.")
else:
    print("We fail to reject H0: No statistically significant difference between algorithms at 95% confidence.")

BP ANOVA: F-statistic = 15.4296, p-value = 0.000000
We reject H0: At least one algorithm performs significantly differently at 95% confidence.

In [31]:
chol_best_hyperparameters = {}

for name, clf in algorithms.items():
    pipe = Pipeline([
        ('preprocessor', preprocessor_c),
        ('classifier', clf)
    ])
    
    grid_search = GridSearchCV(
        pipe,
        param_grids[name],
        cv=5,
        scoring='f1_weighted',
        n_jobs=-1
    )
    grid_search.fit(chol_X, chol_y)
    
    chol_best_hyperparameters[name] = {
        'best_params': grid_search.best_params_,
        'best_score': round(grid_search.best_score_, 4)
    }
    print(f"{name}: {grid_search.best_score_:.4f} — {grid_search.best_params_}")

pd.DataFrame({name: info for name, info in chol_best_hyperparameters.items()}).T

Decision Stump: 0.5067 — {'classifier__criterion': 'gini', 'classifier__splitter': 'best'}
Decision Tree: 0.5420 — {'classifier__criterion': 'gini', 'classifier__max_depth': 10, 'classifier__min_samples_leaf': 5, 'classifier__min_samples_split': 2}
Random Forest: 0.5351 — {'classifier__max_depth': 20, 'classifier__min_samples_leaf': 1, 'classifier__min_samples_split': 2, 'classifier__n_estimators': 100}
Gradient Boosting: 0.5486 — {'classifier__learning_rate': 0.2, 'classifier__max_depth': 5, 'classifier__min_samples_split': 2, 'classifier__n_estimators': 1000}
Support Vector Machine: 0.5374 — {'classifier__C': 10, 'classifier__gamma': 'scale', 'classifier__kernel': 'rbf'}
Naive Bayes: 0.0971 — {'classifier__var_smoothing': 1e-05}
Logistic Regression: 0.5137 — {'classifier__C': 1, 'classifier__max_iter': 1000, 'classifier__solver': 'lbfgs'}
Stochastic Gradient Descent: 0.5384 — {'classifier__alpha': 0.001, 'classifier__loss': 'modified_huber', 'classifier__max_iter': 1000, 'classifier__penalty': 'l2'}

,best_params,best_score
Decision Stump,"{'classifier__criterion': 'gini', 'classifier_...",0.5067
Decision Tree,"{'classifier__criterion': 'gini', 'classifier_...",0.542
Random Forest,"{'classifier__max_depth': 20, 'classifier__min...",0.5351
Gradient Boosting,"{'classifier__learning_rate': 0.2, 'classifier...",0.5486
Support Vector Machine,"{'classifier__C': 10, 'classifier__gamma': 'sc...",0.5374
Naive Bayes,{'classifier__var_smoothing': 1e-05},0.0971
Logistic Regression,"{'classifier__C': 1, 'classifier__max_iter': 1...",0.5137
Stochastic Gradient Descent,"{'classifier__alpha': 0.001, 'classifier__loss...",0.5384

In [32]:
chol_algorithms = {
    'Decision Stump': DecisionTreeClassifier(max_depth=1, criterion='gini', splitter='best', random_state=42),
    'Decision Tree': DecisionTreeClassifier(criterion='gini', max_depth=10, min_samples_leaf=5, min_samples_split=2, random_state=42),
    'Random Forest': RandomForestClassifier(max_depth=20, min_samples_leaf=1, min_samples_split=2, n_estimators=100, random_state=42),
    'Gradient Boosting': GradientBoostingClassifier(learning_rate=0.2, max_depth=5, min_samples_split=2, n_estimators=1000, random_state=42),
    'Support Vector Machine': SVC(C=10, gamma='scale', kernel='rbf', random_state=42),
    'Naive Bayes': GaussianNB(var_smoothing=1e-05),
    'Logistic Regression': LogisticRegression(C=1, max_iter=1000, solver='lbfgs', random_state=42),
    'Stochastic Gradient Descent': SGDClassifier(alpha=0.001, loss='modified_huber', max_iter=1000, penalty='l2', random_state=42)
}

In [33]:
chol_cv_results = {}

for name, model in chol_algorithms.items():
    pipeline = Pipeline([
        ('preprocessor', preprocessor_c),
        ('classifier', model)
    ])
    cv = cross_validate(pipeline, chol_X, chol_y, cv=10, scoring=scoring)
    chol_cv_results[name] = cv

chol_cv_results

{'Decision Stump': {'fit_time': array([0.02293158, 0.02255559, 0.02504873, 0.02403069, 0.02103925,
         0.01712203, 0.01751804, 0.01602411, 0.01603293, 0.01702356]),
  'score_time': array([0.01359439, 0.01403809, 0.01402807, 0.01352262, 0.01301622,
         0.00901937, 0.00901747, 0.00901914, 0.01103258, 0.01101875]),
  'test_accuracy': array([0.64563107, 0.64563107, 0.64563107, 0.64563107, 0.64563107,
         0.64476886, 0.64476886, 0.64476886, 0.64720195, 0.64720195]),
  'test_f1_weighted': array([0.50660137, 0.50660137, 0.50660137, 0.50660137, 0.50660137,
         0.50551404, 0.50551404, 0.50551404, 0.5085841 , 0.5085841 ]),
  'test_recall_weighted': array([0.64563107, 0.64563107, 0.64563107, 0.64563107, 0.64563107,
         0.64476886, 0.64476886, 0.64476886, 0.64720195, 0.64720195])},
 'Decision Tree': {'fit_time': array([0.02904749, 0.02805614, 0.02803111, 0.03410268, 0.02861452,
         0.02855158, 0.0281291 , 0.02868629, 0.02903867, 0.02754903]),
  'score_time': array([0.00902152, 0.0080204 , 0.00851274, 0.01252675, 0.01055717,
         0.00902128, 0.00918627, 0.00902081, 0.00902057, 0.01001835]),
  'test_accuracy': array([0.56796117, 0.56067961, 0.56067961, 0.5631068 , 0.59951456,
         0.59367397, 0.58150852, 0.59367397, 0.58394161, 0.55961071]),
  'test_f1_weighted': array([0.53209978, 0.52959913, 0.51010458, 0.5258161 , 0.53414958,
         0.56162584, 0.52774481, 0.54659004, 0.52926725, 0.51902196]),
  'test_recall_weighted': array([0.56796117, 0.56067961, 0.56067961, 0.5631068 , 0.59951456,
         0.59367397, 0.58150852, 0.59367397, 0.58394161, 0.55961071])},
 'Random Forest': {'fit_time': array([0.38390732, 0.37967992, 0.38297296, 0.38826156, 0.38825035,
         0.38524652, 0.37921715, 0.38834119, 0.40919757, 0.37864399]),
  'score_time': array([0.02003574, 0.02003479, 0.02103591, 0.02011871, 0.02003598,
         0.02003551, 0.02344656, 0.0201056 , 0.02106285, 0.02204967]),
  'test_accuracy': array([0.63106796, 0.63592233, 0.65048544, 0.65048544, 0.64563107,
         0.62773723, 0.64963504, 0.63260341, 0.62043796, 0.63017032]),
  'test_f1_weighted': array([0.52694813, 0.53642478, 0.55145767, 0.55383749, 0.54566236,
         0.52136432, 0.5480074 , 0.54089298, 0.51554398, 0.52414721]),
  'test_recall_weighted': array([0.63106796, 0.63592233, 0.65048544, 0.65048544, 0.64563107,
         0.62773723, 0.64963504, 0.63260341, 0.62043796, 0.63017032])},
 'Gradient Boosting': {'fit_time': array([25.0239296 , 24.87819171, 24.62741971, 24.55510235, 24.60917473,
         24.54277229, 24.5191164 , 24.34914088, 24.36440086, 24.47421622]),
  'score_time': array([0.0265429 , 0.02996063, 0.02908897, 0.02608395, 0.02453089,
         0.02508783, 0.02454066, 0.02461791, 0.02504873, 0.02457643]),
  'test_accuracy': array([0.53883495, 0.57038835, 0.57281553, 0.60679612, 0.59466019,
         0.59610706, 0.57664234, 0.58394161, 0.58394161, 0.57664234]),
  'test_f1_weighted': array([0.50384778, 0.52125795, 0.52901977, 0.56295795, 0.55491555,
         0.5561462 , 0.54036721, 0.53177597, 0.54086513, 0.51760372]),
  'test_recall_weighted': array([0.53883495, 0.57038835, 0.57281553, 0.60679612, 0.59466019,
         0.59610706, 0.57664234, 0.58394161, 0.58394161, 0.57664234])},
 'Support Vector Machine': {'fit_time': array([0.5932498 , 0.6041131 , 0.60857844, 0.60933185, 0.60596585,
         0.62726188, 0.62570286, 0.59609461, 0.58058643, 0.58693337]),
  'score_time': array([0.07611275, 0.08117962, 0.07472205, 0.07422566, 0.07876992,
         0.07466745, 0.07559538, 0.07564616, 0.07366514, 0.07610154]),
  'test_accuracy': array([0.61650485, 0.59223301, 0.59708738, 0.63349515, 0.61893204,
         0.60583942, 0.64476886, 0.62043796, 0.60340633, 0.61313869]),
  'test_f1_weighted': array([0.5380666 , 0.50697779, 0.52903817, 0.56717164, 0.54472954,
         0.53130812, 0.55273437, 0.55169352, 0.52599772, 0.53504822]),
  'test_recall_weighted': array([0.61650485, 0.59223301, 0.59708738, 0.63349515, 0.61893204,
         0.60583942, 0.64476886, 0.62043796, 0.60340633, 0.61313869])},
 'Naive Bayes': {'fit_time': array([0.01403499, 0.01451659, 0.01405668, 0.01402378, 0.01401615,
         0.01403832, 0.0140276 , 0.0145154 , 0.0140388 , 0.01402783]),
  'score_time': array([0.00905752, 0.00903368, 0.00803232, 0.00902033, 0.00901985,
         0.00750494, 0.00852513, 0.00901484, 0.00750518, 0.00901985]),
  'test_accuracy': array([0.14320388, 0.12864078, 0.14805825, 0.15291262, 0.12621359,
         0.12652068, 0.15085158, 0.15815085, 0.16545012, 0.1216545 ]),
  'test_f1_weighted': array([0.09472295, 0.08207856, 0.11075974, 0.10488664, 0.07674058,
         0.06479453, 0.09833483, 0.13053002, 0.13184505, 0.0649278 ]),
  'test_recall_weighted': array([0.14320388, 0.12864078, 0.14805825, 0.15291262, 0.12621359,
         0.12652068, 0.15085158, 0.15815085, 0.16545012, 0.1216545 ])},
 'Logistic Regression': {'fit_time': array([0.04606342, 0.0474143 , 0.04737568, 0.0467844 , 0.04725671,
         0.04318523, 0.04587746, 0.04552627, 0.04636478, 0.05136085]),
  'score_time': array([0.00951838, 0.00850463, 0.00802064, 0.00901985, 0.00800085,
         0.01003003, 0.01001358, 0.00901842, 0.00850844, 0.01133323]),
  'test_accuracy': array([0.64563107, 0.64805825, 0.64805825, 0.64320388, 0.64805825,
         0.64720195, 0.63746959, 0.63990268, 0.64233577, 0.63746959]),
  'test_f1_weighted': array([0.51093653, 0.5163713 , 0.51753549, 0.50544234, 0.51703446,
         0.51530564, 0.51094043, 0.51375312, 0.51051769, 0.50391355]),
  'test_recall_weighted': array([0.64563107, 0.64805825, 0.64805825, 0.64320388, 0.64805825,
         0.64720195, 0.63746959, 0.63990268, 0.64233577, 0.63746959])},
 'Stochastic Gradient Descent': {'fit_time': array([0.0842967 , 0.06107712, 0.06515241, 0.06909037, 0.0675838 ,
         0.08892894, 0.07217836, 0.07218862, 0.08766222, 0.08114982]),
  'score_time': array([0.00800776, 0.00801516, 0.00901127, 0.05807447, 0.00851083,
         0.01301575, 0.00901198, 0.00907993, 0.01001263, 0.00913429]),
  'test_accuracy': array([0.62864078, 0.6092233 , 0.62135922, 0.63106796, 0.64563107,
         0.61313869, 0.63990268, 0.59367397, 0.63990268, 0.63746959]),
  'test_f1_weighted': array([0.52336361, 0.53535647, 0.54434153, 0.54358817, 0.57797469,
         0.52423062, 0.55922707, 0.51927665, 0.52168926, 0.52482682]),
  'test_recall_weighted': array([0.62864078, 0.6092233 , 0.62135922, 0.63106796, 0.64563107,
         0.61313869, 0.63990268, 0.59367397, 0.63990268, 0.63746959])}}

In [34]:
chol_summary = pd.DataFrame({
    name: {
        'Accuracy (mean)': cv['test_accuracy'].mean().round(4),
        'Accuracy (std)': cv['test_accuracy'].std().round(4),
        'F1 Weighted (mean)': cv['test_f1_weighted'].mean().round(4),
        'F1 Weighted (std)': cv['test_f1_weighted'].std().round(4),
        'Recall Weighted (mean)': cv['test_recall_weighted'].mean().round(4),
        'Recall Weighted (std)': cv['test_recall_weighted'].std().round(4),
    }
    for name, cv in chol_cv_results.items()
}).T

chol_summary

,Accuracy (mean),Accuracy (std),F1 Weighted (mean),F1 Weighted (std),Recall Weighted (mean),Recall Weighted (std)
Decision Stump,0.6457,0.0008,0.5067,0.0011,0.6457,0.0008
Decision Tree,0.5764,0.0150,0.5316,0.0135,0.5764,0.0150
Random Forest,0.6374,0.0103,0.5364,0.0129,0.6374,0.0103
Gradient Boosting,0.5801,0.0176,0.5359,0.0179,0.5801,0.0176
Support Vector Machine,0.6146,0.0153,0.5383,0.0159,0.6146,0.0153
Naive Bayes,0.1422,0.0146,0.0960,0.0230,0.1422,0.0146
Logistic Regression,0.6437,0.0041,0.5122,0.0045,0.6437,0.0041
Stochastic Gradient Descent,0.6260,0.0157,0.5374,0.0182,0.6260,0.0157

In [35]:
chol_accuracy_by_algorithm = [chol_cv_results[name]['test_accuracy'] for name in algorithms]

f_stat, p_value = f_oneway(*chol_accuracy_by_algorithm)
print(f"CHOL ANOVA: F-statistic = {f_stat:.4f}, p-value = {p_value:.6f}")

if p_value < 0.05: # H0 = null hypothesis, that all algorithms perform the same
    print("We reject H0: At least one algorithm performs significantly differently at 95% confidence.")
else:
    print("We fail to reject H0: No statistically significant difference between algorithms at 95% confidence.")

CHOL ANOVA: F-statistic = 1549.8253, p-value = 0.000000
We reject H0: At least one algorithm performs significantly differently at 95% confidence.

## Model Submission for Project Step 2

In [36]:
import cloudpickle
from sklearn.base import BaseEstimator, TransformerMixin

class NHANESCleaner(BaseEstimator, TransformerMixin):
    def fit(self, X, y=None):
        return self
    
    def transform(self, X):
        df = X.copy()
        
        hiq_cols = ['HIQ032A', 'HIQ032B', 'HIQ032D', 'HIQ032F', 'HIQ032H', 'HIQ032I']
        for col in hiq_cols:
            if col in df.columns:
                df[col] = df[col].notna().astype(int)
        
        binary_remap = ['RIAGENDR', 'DMQMILIZ', 'DMDBORN4', 'ALQ111', 'ALQ151',
                        'HIQ011', 'HIQ210', 'INQ300']
        for col in binary_remap:
            if col in df.columns:
                df[col] = df[col].map({1: 1, 2: 0})
        
        cols_to_drop = ['SEQN', 'SDDSRVYR', 'RIDSTATR', 
                        'BPXOSY1', 'BPXODI1', 'LBXTC',
                        'BP', 'CHOL']
        df = df.drop(columns=[c for c in cols_to_drop if c in df.columns])
        
        return df

In [37]:
nominal_cols = ['RIDRETH1', 'DMDMARTZ']
numeric_cols = ['RIAGENDR', 'RIDAGEYR', 'DMQMILIZ', 'DMDBORN4', 'DMDYRUSR',
                'DMDEDUC2', 'DMDHHSIZ', 'WTINT2YR', 'WTMEC2YR', 'ALQ111',
                'ALQ121', 'ALQ130', 'ALQ151', 'ALQ170', 'HIQ011', 'HIQ032A',
                'HIQ032B', 'HIQ032D', 'HIQ032F', 'HIQ032H', 'HIQ032I', 'HIQ210',
                'INDFMMPC', 'INQ300', 'IND310']

def make_feature_preprocessor():
    return ColumnTransformer([
        ('num', Pipeline([
            ('imputer', SimpleImputer(strategy='median')),
            ('scaler', StandardScaler())
        ]), numeric_cols),
        ('nom', Pipeline([
            ('imputer', SimpleImputer(strategy='most_frequent')),
            ('encoder', OneHotEncoder(handle_unknown='ignore', sparse_output=False))
        ]), nominal_cols)
    ])

In [38]:
nhanes_raw = pd.read_csv('nhanes.csv')
nhanes_raw['BP'] = nhanes_raw.apply(classify_bp, axis=1)

bp_train, _ = train_test_split(nhanes_raw, test_size=0.2, random_state=42)
bp_train = bp_train.dropna(subset=['BP'])

bp_X_sub = bp_train.drop(columns=['BP'])
bp_y_sub = bp_train['BP']

bp_submit_pipeline = Pipeline([
    ('cleaner', NHANESCleaner()),
    ('features', make_feature_preprocessor()),
    ('classifier', GradientBoostingClassifier(
        learning_rate=0.01, max_depth=3, min_samples_split=2,
        n_estimators=500, random_state=42
    ))
])

bp_submit_pipeline.fit(bp_X_sub, bp_y_sub)

Pipeline(steps=[('cleaner', NHANESCleaner()),
                ('features',
                 ColumnTransformer(transformers=[('num',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='median')),
                                                                  ('scaler',
                                                                   StandardScaler())]),
                                                  ['RIAGENDR', 'RIDAGEYR',
                                                   'DMQMILIZ', 'DMDBORN4',
                                                   'DMDYRUSR', 'DMDEDUC2',
                                                   'DMDHHSIZ', 'WTINT2YR',
                                                   'WTMEC2YR', 'ALQ111',
                                                   'ALQ121', 'ALQ130', 'ALQ151',
                                                   'ALQ170', 'HIQ011',
                                                   'HIQ032A',...
                                                   'HIQ032D', 'HIQ032F',
                                                   'HIQ032H', 'HIQ032I',
                                                   'HIQ210', 'INDFMMPC',
                                                   'INQ300', 'IND310']),
                                                 ('nom',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='most_frequent')),
                                                                  ('encoder',
                                                                   OneHotEncoder(handle_unknown='ignore',
                                                                                 sparse_output=False))]),
                                                  ['RIDRETH1', 'DMDMARTZ'])])),
                ('classifier',
                 GradientBoostingClassifier(learning_rate=0.01,
                                            n_estimators=500,
                                            random_state=42))])

In [39]:
test_predictions = bp_submit_pipeline.predict(pd.read_csv('nhanes.csv').head())
print(test_predictions)

['abnormal' 'normal' 'normal' 'abnormal' 'normal']

In [40]:
with open('model.pkl', 'wb') as f:
    cloudpickle.dump(bp_submit_pipeline, f)

In [41]:
from huggingface_hub import login, HfApi
from submit import upload_files

login()
api = HfApi()
result = upload_files(api, 'ShohruzE/project-step2-bp-model', display_func=display)
print(result)

Processing Files (0 / 0): |          |  0.00B /  0.00B

New Data Upload: |          |  0.00B /  0.00B

CommitInfo(commit_url='https://huggingface.co/ShohruzE/project-step2-bp-model/commit/8b54a8509ca03672893735ecdb7dead3d7ced393', commit_message='Upload model.pkl with huggingface_hub', commit_description='', oid='8b54a8509ca03672893735ecdb7dead3d7ced393', pr_url=None, repo_url=RepoUrl('https://huggingface.co/ShohruzE/project-step2-bp-model', endpoint='https://huggingface.co', repo_type='model', repo_id='ShohruzE/project-step2-bp-model'), pr_revision=None, pr_num=None)

CommitInfo(commit_url='https://huggingface.co/ShohruzE/project-step2-bp-model/commit/0e78040b717b6d18551ab74ecfb1bb99d2491962', commit_message='Upload pyproject.toml with huggingface_hub', commit_description='', oid='0e78040b717b6d18551ab74ecfb1bb99d2491962', pr_url=None, repo_url=RepoUrl('https://huggingface.co/ShohruzE/project-step2-bp-model', endpoint='https://huggingface.co', repo_type='model', repo_id='ShohruzE/project-step2-bp-model'), pr_revision=None, pr_num=None)

CommitInfo(commit_url='https://huggingface.co/ShohruzE/project-step2-bp-model/commit/b1b6ef92675dcda864305861868783fa42b0108d', commit_message='Upload .python-version with huggingface_hub', commit_description='', oid='b1b6ef92675dcda864305861868783fa42b0108d', pr_url=None, repo_url=RepoUrl('https://huggingface.co/ShohruzE/project-step2-bp-model', endpoint='https://huggingface.co', repo_type='model', repo_id='ShohruzE/project-step2-bp-model'), pr_revision=None, pr_num=None)

{'repo_id': 'ShohruzE/project-step2-bp-model'}

In [42]:
nhanes_raw2 = pd.read_csv('nhanes.csv')
nhanes_raw2['CHOL'] = nhanes_raw2['LBXTC'].apply(classify_cholesterol)

chol_train, _ = train_test_split(nhanes_raw2, test_size=0.2, random_state=42)
chol_train = chol_train.dropna(subset=['CHOL'])

chol_X_sub = chol_train.drop(columns=['CHOL'])
chol_y_sub = chol_train['CHOL']

chol_submit_pipeline = Pipeline([
    ('cleaner', NHANESCleaner()),
    ('features', make_feature_preprocessor()),
    ('classifier', SGDClassifier(
        alpha=0.001, loss='modified_huber', max_iter=1000,
        penalty='l2', random_state=42
    ))
])

chol_submit_pipeline.fit(chol_X_sub, chol_y_sub)

test_predictions = chol_submit_pipeline.predict(pd.read_csv('nhanes.csv').head())
print(test_predictions)

with open('model.pkl', 'wb') as f:
    cloudpickle.dump(chol_submit_pipeline, f)

result = upload_files(api, 'ShohruzE/project-step2-chol-model', display_func=display)
print(result)

['normal' 'normal' 'normal' 'normal' 'normal']

Processing Files (0 / 0): |          |  0.00B /  0.00B

New Data Upload: |          |  0.00B /  0.00B

CommitInfo(commit_url='https://huggingface.co/ShohruzE/project-step2-chol-model/commit/9171eb9af4aaafb826007454406d0f8de40e9d40', commit_message='Upload model.pkl with huggingface_hub', commit_description='', oid='9171eb9af4aaafb826007454406d0f8de40e9d40', pr_url=None, repo_url=RepoUrl('https://huggingface.co/ShohruzE/project-step2-chol-model', endpoint='https://huggingface.co', repo_type='model', repo_id='ShohruzE/project-step2-chol-model'), pr_revision=None, pr_num=None)

CommitInfo(commit_url='https://huggingface.co/ShohruzE/project-step2-chol-model/commit/0cf665f7108e90e76dadfc17c141219bc81c1ccf', commit_message='Upload pyproject.toml with huggingface_hub', commit_description='', oid='0cf665f7108e90e76dadfc17c141219bc81c1ccf', pr_url=None, repo_url=RepoUrl('https://huggingface.co/ShohruzE/project-step2-chol-model', endpoint='https://huggingface.co', repo_type='model', repo_id='ShohruzE/project-step2-chol-model'), pr_revision=None, pr_num=None)

CommitInfo(commit_url='https://huggingface.co/ShohruzE/project-step2-chol-model/commit/1be0aadabcd9fade725bf1ad56908a6ac79fc1ac', commit_message='Upload .python-version with huggingface_hub', commit_description='', oid='1be0aadabcd9fade725bf1ad56908a6ac79fc1ac', pr_url=None, repo_url=RepoUrl('https://huggingface.co/ShohruzE/project-step2-chol-model', endpoint='https://huggingface.co', repo_type='model', repo_id='ShohruzE/project-step2-chol-model'), pr_revision=None, pr_num=None)

{'repo_id': 'ShohruzE/project-step2-chol-model'}